config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end

      resources :questions, only: %i[index create show], shallow: true do
        resources :answers, only: %i[show create index]
      end
    end
  end

  concern :votable do
    member do
      post :voteup
      post :votedown
    end
  end

  concern :commentable do
    resources :comments,  only: %i[create update destroy]
  end

  resources :questions,  concerns: [:votable, :commentable] do
    # member do
    #   post :subscribe
    #   delete :unsubscribe
    # end
    resources :answers, concerns: [:votable, :commentable], shallow: true, only: %i[create update destroy] do
      post :accept_answer, on: :member
    end
  end

  resources :subscriptions, only: %i[create destroy]

  resources :attachments

  root to: 'questions#index'
  get '/search' => 'search#search'
  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :attachments, as: :attachable
  belongs_to :user

  validates :title, :body, presence: true

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  def matched_user?(current_user)
    current_user.id == user_id
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  def index
    @questions = Question.all
    respond_with @questions
  end

  def show
    @question = Question.find(params[:id])
    respond_with @question
  end

  def create
    respond_with current_resource_owner.questions.create(question_params)
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  respond_to :html, :json, :js

  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show edit update destroy]
  before_action :build_answer, only: %i[show]

  after_action :publish_question, only: %i[create]

  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with (@question.comments.new)
  end

  def new
    @question = Question.new
    respond_with (@question.attachments.build)
  end

  def edit; end

  def create
    respond_with( @question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params) if current_user.author_of?(@question)
    respond_with @question
  end

  def destroy
    respond_with(@question.destroy) if current_user.author_of?(@question)||current_user.admin?
    flash.discard
  end

  private

  def load_question
    @question = Question.find(params[:id])
    gon.question_id = @question.id
  end

  def build_answer
    @answer = @question.answers.build
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: %i[file id _destroy])
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast('questions',
                                 ApplicationController.render(
                                     partial: 'common/question_list',
                                     locals: { question: @question }
                                 )
    )
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/questions/_attachment_fields.html.slim
.nested-fields
  .field
    = f.label :file
    = f.file_field :file
  = link_to_remove_association "remove attachment", f

app/views/questions/_attachments.html.slim
h3 Attachments
        ul
          - question.attachments.each do |attachment|
            div id="question_attachment-id-#{attachment.id}"
              p= link_to attachment.file.identifier, attachment.file.url
            - if can?(:destroy, question)
              p= link_to 'Delete', attachment, remote: true, method: :delete, data: { attachmnet_id: attachment.id }

app/views/questions/_form.html.slim
= form_for @question  do |f|
  =render 'common/errors', resource: @question
  .form-group
    h2
      = f.label :title
    p
      = f.text_field :title, class: "form-control"
  .form-group
    h2
      = f.label :body
    p
      = f.text_area :body, class: "form-control"
    p Attachments:
    = render 'common/edit_attachment_form', f: f

    p
      = f.submit "#{ @question.new_record? ? 'Create' : 'Save' } ", class: "btn btn-primary btn-lg btn-block", role: "button"

app/views/questions/_question.html.slim
div class="question questions" id="question-id-#{question.id}" data-id="#{question.id}"
    div class="question-container panel panel-default"
      div.panel-heading
        h3
          | Question:
          = question.title
      div.panel-body
        = question.body
      - if  question.attachments.any?
        div class="panel panel-default"
          div.panel-heading  Attachments
          ul
            - question.attachments.each do |attachment|
              div id="question_attachment-id-#{attachment.id}"
                p= link_to attachment.file.identifier, attachment.file.url
              - if can?(:destroy, question)
                p= link_to 'Delete', attachment, remote: true, method: :delete, data: { attachmnet_id: attachment.id }

      - if can?(:voteup, question)
        div  class="rating"
          div class="panel panel-default"
            div.panel-heading
              p Votes:
            div.panel-body
              span = link_to  voteup_question_path(question), method: :post, data: {type: :json, question_id: question.id}, remote: true, class: 'btn btn-primary'
                  i.fa.fa-angle-up.fa-3x
              span id="question_rate-id-#{question.id}" = question.rate
              span = link_to  votedown_question_path(question), method: :post, data: {type: :json, question_id: question.id}, remote: true, class: 'btn btn-primary'
                  i.fa.fa-angle-down.fa-3x
      = render 'common/comments', resource: question
      = render 'common/subscription', resource: question

app/views/questions/destroy.js.erb
$('#question-id-<%= @question.id %>').remove();
$('.notice').append('<div class="alert fade in alert-success"><button type="button" class="close" data-dismiss="alert">×</button><%= j = flash.notice = 'Question was successfully destroyed.' %></p>');

app/views/questions/edit.html.slim
=render @question
=render 'form', resource: @question

app/views/questions/index.html.slim
table.table.table-hover
   thead
     tr
       th.col-md-1 scope="col" Number
       th.col-md-5 scope="col" Question
       th.col-md-2 scope="col" Author
       th.col-md-2 scope="col" Created
       th.col-md-1 scope="col"
       th.col-md-1 scope="col"
   tbody
       - @questions.each do |question|
         tr id="question-id-#{question.id}"
          th scope="row"
            = question.id
            td = link_to question.title, question
            td = question.user.email
            td = question.created_at
          .question
            td = link_to 'Edit', edit_question_path(question) if can?(:destroy, question) if can?(:destroy, question)
            td = link_to 'Delete', question, remote: true, method: :delete, data: {question_id: question.id} if can?(:destroy, question)
- if can?(:create, Question)
  .btn.btn-primary.btn-lg.btn-block
    = link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
.container
  h1.page_question_title New Question
  =render 'form', resource: @question

app/views/questions/show.html.slim
= render @question
div class="panel panel-default"
  div class="panel-heading"
    h3 Answers
  .answers
    = render @question.answers.sort_by_best
  -if user_signed_in?
    = form_for [@question, @answer], remote: true do |f|
       .form_gr
        .field
          = f.label :body, 'Your answer'
        .answer-errors
          = f.text_area :body
        .attachments
          = f.fields_for :attachments, @answer.attachments.new do |a|
            = render 'answers/attachment_fields', f: a
          .links
            =link_to_add_association 'add attachment', f, :attachments
        p = f.submit 'Create'

          .back
            =link_to 'Назад', questions_path