config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end

      resources :questions, only: %i[index create show], shallow: true do
        resources :answers, only: %i[show create index]
      end
    end
  end

  concern :votable do
    member do
      post :voteup
      post :votedown
    end
  end

  concern :commentable do
    resources :comments,  only: %i[create update destroy]
  end

  resources :questions,  concerns: [:votable, :commentable] do
    # member do
    #   post :subscribe
    #   delete :unsubscribe
    # end
    resources :answers, concerns: [:votable, :commentable], shallow: true, only: %i[create update destroy] do
      post :accept_answer, on: :member
    end
  end

  resources :subscriptions, only: %i[create destroy]

  resources :attachments

  root to: 'questions#index'
  get '/search' => 'search#search'
  mount ActionCable.server => '/cable'
end

app/models/search.rb
class Search
  CATEGORIES = %w(Questions Answers Comments Users)

  def self.find(query, category)
    secure_query = ThinkingSphinx::Query.escape(query)
    if CATEGORIES.include?(category)
      model = category.singularize.classify.constantize
      model.search secure_query
    else
      ThinkingSphinx.search secure_query
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def search
      @query = params[:query]
      @category = params[:category]
      @results = Search.find(@query, @category) if @query.present?
    end
end

app/views/search/search.html.slim
.results
  - if @results.present?
    h3 Search results #{@query}
    ul
      - @results.each do |result|
        li
          p= result.class.to_s
          - case result.class.to_s
          - when "Question"
            = link_to result.title, result
          - when "Answer"
            = link_to result.body, result.question
          - when "Comment"
            - if result.commentable_type == 'Question'
              = link_to result.body, question_path(result.commentable_id)
            - else
              = link_to result.body, question_path(result.commentable.question)
          - when "User"
            = result.email
  - else
    p No results