config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end

      resources :questions, only: %i[index create show], shallow: true do
        resources :answers, only: %i[show create index]
      end
    end
  end

  concern :votable do
    member do
      post :voteup
      post :votedown
    end
  end

  concern :commentable do
    resources :comments,  only: %i[create update destroy]
  end

  resources :questions,  concerns: [:votable, :commentable] do
    # member do
    #   post :subscribe
    #   delete :unsubscribe
    # end
    resources :answers, concerns: [:votable, :commentable], shallow: true, only: %i[create update destroy] do
      post :accept_answer, on: :member
    end
  end

  resources :subscriptions, only: %i[create destroy]

  resources :attachments

  root to: 'questions#index'
  get '/search' => 'search#search'
  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, optional: true, touch: true
  belongs_to :user
  has_many :attachments, as: :attachable

  validates :body, presence: true

  scope :sort_by_best, -> { order(best: :desc) }

  accepts_nested_attributes_for :attachments, reject_if: :all_blank, allow_destroy: true

  after_create :dispatch_new_answer, on: :create

  def set_as_best
    return if reload.best?

    transaction do
      question.answers.update_all(best: false)
      update!(best: true)
    end
  end

  def matched_user?(current_user)
    current_user.id == user_id
  end

  protected

  def dispatch_new_answer
    NewAnswerDispatchJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  respond_to :js
  respond_to :json, only: %i[create]

  before_action :authenticate_user!
  before_action :set_question, only: %i[new create]
  before_action :set_answer, only: %i[show destroy update accept_answer ]
  after_action :publish_answer, only: %i[create]

  authorize_resource

  def create
    @answer = current_user.answers.create(answer_params.merge(question_id: @question.id))
    @answer.question = @question
    respond_with(@answer)
  end

  def update
    @question = @answer.question
    respond_with(@answer.update(answer_params))
  end

  def destroy
    @question = @answer.question
    respond_with(@answer.destroy) if current_user.author_of?(@answer)
  end

  def accept_answer
    @question = @answer.question

    if current_user.author_of?(@question)
      @answer = @question.answers.find(params[:id])
      @answer.set_as_best
    else
      flash[:notice] = 'You can\'t accept the answer for the question, that is not yours'
    end
  end

  protected
  def publish_answer

    if @answer.nil?
      set_answer
      @question = @answer.question
      created = false
    else
      created = true
    end
    return if @answer.errors.any?

    data = @answer.as_json.merge(voted: @answer.matched_user?(current_user),
                                 rate: @answer.rate,
                                 created: created,
                                 question_user: @answer.question.user.id,
                                 attachments: @answer.attachments.map do |attach|
                                   { id: attach.id, filename: attach.file.filename, url: attach.file.url }
                                 end)


    logger.debug data
    ActionCable.server.broadcast("questions_#{@question.id}",
                                 data: data
    )
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: %i[file id _destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :set_question, only: %i[index create]

  def index
    respond_with @question.answers
  end

  def show
    @answer = Answer.find(params[:id])
    respond_with @answer
  end

  def create
    @answer = Answer.create(answer_params.merge(user: current_resource_owner, question: @question))
    respond_with @answer
  end

  def answer_params
    params.require(:answer).permit(:body)
  end

  protected

  def set_question
    @question = Question.find(params[:question_id])
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
    div id="answer-id-#{answer.id}" class="#{'best_answer' if answer.best?}" class="answer"
      div class = 'answer-container-#{answer.id}' class="panel panel-default"
        div.panel-heading
          p = answer.user.email
        div.panel-body
          p = answer.body
        - if answer.attachments.any?
          div class="panel panel-default"
            div.panel-heading  Attachments
            ul
              - answer.attachments.each do |a|
                div id="answer_attachment-id-#{a.id}"
                  p= link_to a.file.identifier, a.file.url
                - if can?(:destroy, answer)
                  p= link_to 'Удалить', a, remote: true, method: :delete, data: { attachmnet_id: a.id }
        - if can?(:voteup, answer)
             div class="rating"
               div class="panel panel-default"
                 div.panel-heading
                   p Votes:
                 div.panel-body
                    span = link_to voteup_answer_path(answer), method: :post, data: {type: :json, answer_id: answer.id}, remote: true, class: 'btn btn-primary'
                      i.fa.fa-angle-up.fa-2x
                    span id="answer_rate-id-#{answer.id}" = answer.rate
                    span = link_to votedown_answer_path(answer), method: :post, data: {type: :json, answer_id: answer.id}, remote: true, class: 'btn btn-primary'
                      i.fa.fa-angle-down.fa-2x
        - if can?(:destroy, answer)
          p
            = link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
          p
            = form_for answer, remote: true, html: { id: "edit-answer-#{answer.id}"}  do |f|
              p
                = f.label :body, "Answer"
              p
                = f.text_area :body
                = render 'common/edit_attachment_form', f: f
              p
                = f.submit 'Save'
          p
            = link_to 'Delete', answer, remote: true, method: :delete, data: { confirm: "You sure?" }

        - if can?(:accept_answer, answer)
          p= button_to 'Accept answer', accept_answer_answer_path(answer), remote: true
        = render 'common/comments', resource: answer

app/views/answers/_attachment_fields.html.slim
.nested-fields
  .field
    = f.label :file
    = f.file_field :file
  = link_to_remove_association "remove attachment", f

app/views/answers/accept_answer.js.erb
$('.answers').html('<%= j render @question.answers.sort_by_best %>');

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
<% @answer.errors.full_messages.each do |message| %>
  $('.answer-errors').html('<%= j message %>');
<% end %>
<% else %>
<% if remotipart_submitted? %>
  $('.answers').html('<%= j "#{render (@question.answers.sort_by_best)}" %>');
<% else %>
  $('.answers').html('<%=  j render (@question.answers.sort_by_best) %>');
<% end %>
$('.edit-answer-link').click(function(e) {
    e.preventDefault();
    $(this).hide();
    answer_id = $(this).data('answerId');
    $('form#edit-answer-' + answer_id).show();
});
  $('.notice').html('<%= j flash.notice = 'Answer was successfully created.' %>');
  $('textarea').val('');
  $('.field input').val('');
<% end %>

app/views/answers/destroy.js.erb
$('#answer-id-<%= @answer.id %>').remove();
$('.notice').html('<%= j flash.notice = 'Answer was successfully destroyed.' %>');

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer_errors').html('<%= j message %>');
  <% end %>
<% else %>
<% if remotipart_submitted? %>
    $('.answers').html('<%= j "#{render (@question.answers.sort_by_best)}" %>');
<% else %>
    $('.answers').html('<%= j render (@question.answers.sort_by_best) %>');
<% end %>
    $('.edit-answer-link').click(function(e) {
        e.preventDefault();
        $(this).hide();
        var answer_id = $(this).data('answerId');
        $('form#edit-answer-' + answer_id).show();
    });
<% end %>