config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
      end

      resources :questions, only: %i[index create show], shallow: true do
        resources :answers, only: %i[show create index]
      end
    end
  end

  concern :votable do
    member do
      post :voteup
      post :votedown
    end
  end

  concern :commentable do
    resources :comments,  only: %i[create update destroy]
  end

  resources :questions,  concerns: [:votable, :commentable] do
    # member do
    #   post :subscribe
    #   delete :unsubscribe
    # end
    resources :answers, concerns: [:votable, :commentable], shallow: true, only: %i[create update destroy] do
      post :accept_answer, on: :member
    end
  end

  resources :subscriptions, only: %i[create destroy]

  resources :attachments

  root to: 'questions#index'
  get '/search' => 'search#search'
  mount ActionCable.server => '/cable'
end

app/views/common/_comments.html.slim
.container
  .row
    .col
      - if user_signed_in?
        h4 Comments
        .comments data-id="#{resource.id}"
            - if resource.comments.present?
            - resource.comments.each do |comment|
              -if comment.persisted?
                div id="comment-id-#{resource.id}-#{comment.id}" class="panel panel-default"
                  div.panel-heading
                    p
                      = comment.created_at
                  div.panel-body
                    p.comment-body
                      = comment.body
                    - if user_signed_in? && can?(:destroy, comment)
                        - if comment.commentable_type == 'Answer'
                            = link_to 'Delete', comment, remote: true, method: :delete, data: { comment_id: comment.id }
                        - else
                          - if comment.commentable_type == 'Question'
                              p
                                = link_to 'Delete', [resource, comment], remote: true, method: :delete, data: { comment_id: comment.id }

      - if user_signed_in?
          = form_for [resource, resource.comments.build], remote: true, data: { type: :json } do |f|
              = f.text_area :body
              br
              = f.submit 'Place a comment'

app/views/common/_edit_attachment_form.html.slim
= f.fields_for :attachments do |attach|
  .nested-fields
    p
      =>attach.object.file.filename
span= link_to_add_association 'add', f, :attachments, partial:'common/file_fields', class: "btn btn-primary", role: "button"

app/views/common/_errors.html.slim
- if resource.errors.any?
  #error_explanation
ul
  - resource.errors.full_messages.each do |message|
        li
          = message

app/views/common/_file_fields.html.slim
.nested-fields.display_inline
  .field
    = f.label :file
    = f.file_field :file
  span = link_to_remove_association "remove", f, class: "btn btn-primary", role: "button"

app/views/common/_question_list.html.slim
li
  div id="question-id-#{question.id}"
    = link_to question.title, question
    .question
      p
        = link_to 'Eddit', edit_question_path(question)
      p
        = link_to 'Delete', question, remote: true, method: :delete, data: { question_id: question.id }

app/views/common/_subscription.html.slim
.subscription
  - if can?(:create, Subscription) && !current_user.subscribed?(@question) && !current_user.author_of?(@question)
    p= button_to 'Subscribe', subscriptions_path(question_id: @question), remote: true
  - @question.subscriptions.each do |subscription|
    - if can?(:destroy, subscription) && current_user.subscribed?(@question)
      p= button_to 'Unsubscribe', subscription_path(subscription), method: :delete, remote: true

app/views/common/subscribe.js.erb
$(".subscription").html('<%= j render 'common/subscription', question: @question %>')